config/routes.rb
Blog::Application.routes.draw do

  devise_for :members,:controllers => { :registrations =>'registration'}
  resources :posts do
  resources :comments
  end

  get "welcome/index"

  root 'home#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}

  has_attached_file :avatar, :command_path => "/usr/local/bin/",
                    :style => {:small => "50x50>"}

  validates_attachment_presence :avatar
  validates_attachment_size :avatar, :less_than => 3.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png', 'image/bmp']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where(:member_email => session[:member_email])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if(member_signed_in?)
      @post.member_email = session[:member_email]
    end

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    if @post.member_email == session[:member_email]
      @post
    else
      redirect_to posts_path
    end
  end

  def edit
    @post = Post.find(params[:id])
    if @post.member_email == session[:member_email]
      @post
    else
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :text, :avatar)
  end
end

app/controllers/registration_controller.rb
class RegistrationController < Devise::RegistrationsController

  def new
    @member= Member.new
  end

  def create
    @member = Member.new(member_params)

    if @member.save
      redirect_to new_member_session_path
    else
      render :action => "new"
    end
  end

  private
  def member_params
    params.require(:member).permit(:email, :password, :password_confirmation, :remember_me, :username)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br />
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/home/index.html.erb
<% if member_signed_in? %>
    <%- model_class = Post -%>
    <div class="page-header">
      <h1><%= 'Welcome' %></h1>
      <b>LOGGED IN MEMBER:</b> <%= current_member[:username] %>
    </div>

    <h3>You have successfully signed in!</h3>
    <% session[:member_email] = current_member[:email] %>
    <%= link_to "Proceed to BLOG", posts_path, :method => :get, :class => 'btn' %>

<% else %>

    <h1> Welcome to BLOG </h1>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <a class="brand" href="#"> BLOG </a>
      <!-- Everything in here gets hidden at 940px or less -->
      <div class="nav-collapse">
        <!-- menu items gets rendered here instead -->
        <ul class="nav">
          <% if member_signed_in? %>
            <li><%= link_to "Sign out", destroy_member_session_path, :method => :delete %></li>
          <% else %>
              <li><%= link_to "Sign-in", new_member_session_path, :method => :get %></li>
              <li><%= link_to "Sign-up", new_member_registration_path, :method => :get %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">

  <div class="row">

    <div class="span12">

      <%= yield %>

    </div>

  </div>

</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>

    <div class="control-group">
      <%= f.label :avatar, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :avatar, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :text, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :text, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.back")),
                  posts_path, :class => 'btn' %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
  <b>LOGGED IN MEMBER:</b> <%= current_member[:username] %>
</div>
<% if member_signed_in? %>

<%= render :partial => 'form' %>
<% else %>

<h1> Welcome to BLOG </h1>

<% end %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <b>LOGGED IN MEMBER:</b> <%= current_member[:username] %>
</div>

<% if member_signed_in? %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_post_path,
                :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:avatar) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:text) %></th>
      <th><%= model_class.human_attribute_name(:member_email) %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= image_tag post.avatar.url %></td>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
        <td><%= post.member_email %></td>

        <td>
          <%= link_to 'Edit', edit_post_path(post), :class => 'btn btn-mini btn-danger' %>
          <%= link_to 'Show', post_path(post), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>

<h1> Welcome to BLOG </h1>

<% end %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
  <b>LOGGED IN MEMBER:</b> <%= current_member[:username] %>
</div>

<% if member_signed_in? %>

    <%= render :partial => 'form' %>
<% else %>

    <h1> Welcome to BLOG </h1>

<% end %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  <b>LOGGED IN MEMBER:</b> <%= current_member[:username] %>
</div>

<% if member_signed_in? %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:avatar) %>:</strong></dt>
  <dd><%= image_tag @post.avatar.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= @post.text %></dd>
  <dt><strong><%= model_class.human_attribute_name(:member_email) %>:</strong></dt>
  <dd><%= @post.member_email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn btn-mini btn-danger' %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn'  %>
</div>

<% else %>

    <h1> Welcome to BLOG </h1>

<% end %>

app/views/welcome/index.html.erb
<h1>Hello World</h1>

<%= link_to "MY BLOG", controller: "posts" %>